name: Build and Push Docker Image to ECR and Redeploy ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::816069165502:role/gh-actions-cliente-service-role
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image for linux/amd64 to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: cliente-service
          IMAGE_TAG: latest
        run: |
          echo "🔁 Buildx com --platform linux/amd64"
          docker buildx build \
            --platform linux/amd64 \
            --no-cache \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --push .

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster microservices-cluster \
            --service cliente-service \
            --force-new-deployment \
            --region us-east-1
